image: registry.znuny.com/znuny/internal/docker-znunylts-ci:6.0.40

include:
  - project: 'Znuny/Internal/Znuny'
    file: '/templates/gitlab/default/default.yml'

default:
  before_script:
    - /run.sh
